repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=25']
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241
    hooks:
      - id: ruff
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-gfm,
            mdformat-black,
        ]
        args: [--wrap, "88"]
        files: (README\.md)
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args: [-v, --fail-under=40, src, tests]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
    -   id: mypy
        args: [
            --no-strict-optional,
            --ignore-missing-imports,
        ]
        additional_dependencies: [
            types-attrs,
            types-click,
            types-setuptools
        ]
        pass_filenames: false
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
    -   id: check-manifest
        args: [--no-build-isolation]
        additional_dependencies: [setuptools-scm, toml]
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
