codecov:
  branch: main

coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default:
        threshold: 1%

ignore:
  - "setup.py"
  - "versioneer.py"
  - "src/latex_dependency_scanner/_version.py"
