name: lds

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.8
  - pip
  - setuptools-scm
  - toml

  # Testing
  - pytest

  # Development
  - black
  - pre-commit
  - tox-conda
