name: lds

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.6
  - pip
  - setuptools-scm
  - toml

  # Testing
  - pytest

  # Development
  - anaconda-client
  - black
  - conda-build
  - conda-verify
  - jupyterlab
  - pre-commit
  - tox-conda
  - versioneer
