name: latex-dependency-scanner

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip

  # Testing
  - pytest

  # Development
  - anaconda-client
  - black
  - conda-build
  - conda-verify
  - jupyterlab
  - pre-commit
  - tox-conda
  - versioneer
